# Generated by Django 4.2.4 on 2023-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
