# Generated by Django 4.2.4 on 2023-08-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='joining_date',
        ),
    ]
